# Generated by Django 2.1.5 on 2022-03-12 11:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('club_description', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('website_url', models.URLField()),
                ('genre', models.CharField(max_length=30)),
                ('location_coordinates', models.CharField(help_text='LNG LAT', max_length=30)),
                ('entry_fee', models.FloatField(default=0.0)),
                ('opening_hours_week', models.CharField(max_length=20)),
                ('opening_hours_weekend', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, default='club_pictures/default_club.png', upload_to='club_pictures')),
                ('covid_test_required', models.BooleanField(default=False)),
                ('underage_visitors_allowed', models.BooleanField(default=False)),
                ('average_rating', models.FloatField(blank=True, default=0.0)),
                ('user_reported_safety', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, default='event_pictures/default_event.png', upload_to='event_pictures')),
                ('happening_at', models.DateTimeField(help_text='MM/DD/YY HH:MM')),
                ('capacity', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_list', to='clubmate.Club')),
            ],
            options={
                'ordering': ['happening_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('rating_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_safe', models.BooleanField(default=False)),
                ('user_commentary', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_upvotes', models.IntegerField(default=0)),
                ('user_reported_safety', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['-number_of_upvotes'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='profile_pictures/default_user.png', upload_to='profile_pictures')),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('clubs', models.ManyToManyField(blank=True, to='clubmate.Club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_written_list', to='clubmate.UserProfile'),
        ),
        migrations.AddField(
            model_name='rating',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_list', to='clubmate.Club'),
        ),
    ]
